reviews:
  enabled: true
  request_changes: true
  target_branches:
    - main
    - develop
  auto_review:
    enabled: true
  auto_fix: true
  timeout: 900000
  exclude_patterns:
    - .spec-workflow/**
    - "*.md"
    - "*.txt"
    - .github/**
    - .venv/**
  review_status: true

chat:
  auto_reply: true
